apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy # — Grafana выступает как прокси: браузер → Grafana → Prometheus
    url: http://prometheus:9090 # это адрес сервера Prometheus внутри Docker-сети.
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 5s
      queryTimeout: 60s
      httpMethod: POST
  - name: Jaeger
    type: jaeger
    url: http://jaeger:16686  # ← UI-порт Jaeger
    access: proxy
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      maxLines: 1000
# Здесь была ошибка с лишним isDefault
# Grafana и Prometheus находятся в одной сети app-network → DNS-имя prometheus разрешается коррект